### ISSUE TITLE
Megapixel theme crashes SimpleMenu (PocketGo)

### ISSUE THREAD

**Issue by nicosensei** [fgl82/simplemenu#103]
Hi,

I put the Megapixels theme into the /mnt/.SimpleMenu/themes folder. When I switch to that theme in SimpleMenu settings, the app crashes. I'm running the latest version to date, and MiyooCFW 1.3.2.

**Comment by pfroo40** [comment]
I have the same issue, I saw on Reddit that the developer of the theme is aware of the issue and just hasn't had a chance to fix it yet.

**Comment by XargonWan** [comment]
Crashes even on RG-350 as previously said, seems like that the theme itself is broken.

**Comment by fgl82** [comment]
Please open a bug with the developer of the theme or a new one here if he finds this is actually simplemenu's fault :)

Thanks!
