### ISSUE TITLE
[feature request] Use different pictures for game list and fullscreen mode

### ISSUE THREAD

**Issue by nicosensei** [fgl82/simplemenu#105]
Hi, currently the image used in the gamelist is the same as the one in fullsecreen browsing mode, only scaled down. It would be nice to be able to use 2 different images, for instance _box2dfront_ in the gamelist, and some mix or screenshot in fullscreen. Also it would possibly avoid rescaling.

**Comment by fgl82** [comment]
I feel this is adding too much complexity for how I want this to work. I will consider it but can't say I will implement it. Thanks for your input.
