### ISSUE TITLE
Question about setup

### ISSUE THREAD

**Issue by trashpanther** [fgl82/simplemenu#107]
In the instructions of how to setup simple menu version 6.1 onto the rg350 I am confused about the fifth step.

What am I supposed to modify in this step shown below?

"Open the .simplemenu folder on your PC and modify the section group ini files under /home/.simplemenu/section_groups"

Also can this whole setup be done on an android phone? I do not have a computer but I have been successful in adding roms to my rg350m with my android phone.

Thank you for any and all help that you may be able to provide!

**Comment by fgl82** [comment]
Hi, basically, "Also can this whole setup be done on an android phone?" -> no, sorry, you need to edit files with a nice text editor

**Comment by fgl82** [comment]
The section group part means you need to modify the files to match your paths for the emulators
