### ISSUE TITLE
RG350M - Can't access favorites

### ISSUE THREAD

**Issue by nicosensei** [fgl82/simplemenu#108]
Hi,

I can't access favorites on RG350M. Pressing power button has no effect. A real shame as everything else is perfectly functional.

**Comment by rferrari81** [comment]
you must press L2 after placing at least one game in your favorites

**Comment by nicosensei** [comment]
Oh boy, do I feel dumb, I missed that completely. It's working with L2, thank you!

Hence, this non issue should be closed ;-)

**Comment by fgl82** [comment]
Closing it :)
