### ISSUE TITLE
[feature request] add overclock menu

### ISSUE THREAD

**Issue by rferrari81** [fgl82/simplemenu#109]
i am experiencing speed problems in RG350M with various games starting them from simplemenu while starting them from emulator they work well.  there is no possibility to overclock as from the system menu?

**Comment by fgl82** [comment]
Last time I checked the RG350, no OC was possible. What CFW are you using, what launcher (other than simplemenu) and why do you say it's the overclocking that's helping your games launch?

**Comment by fgl82** [comment]
Closing, since no answer
