### ISSUE TITLE
[question] Previews for apps and games

### ISSUE THREAD

**Issue by nicosensei** [fgl82/simplemenu#110]
I've tried to put a png in _/media/data/apps/media_, but no preview is showing in the _apps & games_ category. Is ot a know limitation, or else can you please explain how can I get previews for apps and games?

**Comment by nicodanyan** [comment]
In order to be visible, your preview must hav that exact same name as your app or port.
For example in my /media/data/apps/boxart/ folder I have GhoulsAndGhostsRemix-0.56-1.png and it's working like a charm for my GhoulsAndGhostsRemix-0.56-1.opk port located in /media/data/apps/. I use boxart instead of media for my preview but it works in the same way.

**Comment by ArKder** [comment]
Hello i'm new at this, i have previews working but i was wondering if there is some way to add both previews (boxart,title or snaps) in simplemenu?

**Comment by dscx** [comment]
@ArKder It seems like you can, but I am not sure on specifics. Check out [this](https://retrogamecorps.com/2020/08/19/guide-simplemenu-on-the-rg350/#Repository) - the 'clear' and 'circuit' themes seem to support box art and preview. You could tweak that, or reach out to its creator.

**Comment by fgl82** [comment]
@nicosensei check this out: https://retrogamecorps.com/2020/08/19/guide-simplemenu-on-the-rg350
Games and Apps: To make SimpleMenu “box art” for your native games or apps, you’ll need to make a “media” folder inside the media/data/apps folder and be sure to name the .png image the same as the .opk file name in the media/data/apps folder. Note that some apps, like the Clock app, don’t have a traditional .opk launcher. Instead, SimpleMenu uses .fgl links to find the actual executable file (which is in usr/bin). So to add box art to these apps you need to make a “media” folder inside the media/data/local/home/.simplemenu/apps/ folder, and its name must match the .fgl file found in the media/data/local/home/.simplemenu/apps/ folder minus the “##_” prefix. So for the “20_pyclock.fgl” file, the image should be placed in media/data/local/home/.simplemenu/apps/media and should be named “pyclock.png”.

**Comment by fgl82** [comment]
@ArKder you can only have one preview per rom, sorry
