### ISSUE TITLE
Version 6.1 crashes on PG2

### ISSUE THREAD

**Issue by GeekGuyMJ** [fgl82/simplemenu#112]
Hello,
Just let you know that I did a clean install of Rogue 1.0.9 and could not get Simple v.6.1 to start. It would crash every time. I followed your instructions for another person that had the same issue and used the RG350 opk instead and it worked great. I hope this helps. Thank you for your hard work on this. It looks great!

**Comment by fgl82** [comment]
Thanks for you input!
