### ISSUE TITLE
Can't access "Favorites" on PG2

### ISSUE THREAD

**Issue by pfroo40** [fgl82/simplemenu#113]
Hi, I'm running a PocketGo 2 v2 on Rogue CFW 1.0.9 using Simplemenu version 6, the RG350 version (the PG2 version crashes, likely because I am on Rogue). I can successfully mark a favorite but can't seem to access the favorites menu after that, I press L2 and nothing happens. Maybe a button mapping difference between the PG2 and RG350?

**Comment by joelvdc** [comment]
Same problem here :/

**Comment by fgl82** [comment]
Probably, if I find the right code I will let you know here. I don't own a PG2 V2

**Comment by fgl82** [comment]
Not supporting PG2 anymore
