### ISSUE TITLE
Simple menu crashes

### ISSUE THREAD

**Issue by knuttyfox** [fgl82/simplemenu#115]
Hi, I’ve installed and configured simple menu on the RG350M and it intermittently crashes, going back to main screen on RG350M. It tends to occur when scrolling through the console emulators and  usually at the Super Nintendo emulator. Any ideas how to resolve this?

Thanks

**Comment by fgl82** [comment]
@knuttyfox I'm releasing a more stable version tomorrow, please let me know afterwards if your issue is fixed.

Meanwhile, take a look here, and see if there's anything you missed.

Thanks.
