### ISSUE TITLE
How to configure ScummVM?

### ISSUE THREAD

**Issue by XargonWan** [fgl82/simplemenu#117]
How to configure it to make SimpleMenu t9olist the games an run them via ScummVM?

**Comment by goldmojo** [comment]
I forked craigsc's scummvm in order to make it work with SimpleMenu.
If interested, you can get this here : https://github.com/goldmojo/scummvm-rg350/releases
and follow the release description, it explains everything.

**Comment by XargonWan** [comment]
Thanks a lot, this solved the issue!
