### ISSUE TITLE
tying images to custom "consoles" game list

### ISSUE THREAD

**Issue by Jerry-in-WA** [fgl82/simplemenu#118]
[edit]  I figured it out.  Not only that, I made 2 high-resolution themes.  (oldskool and blackpixel)  perhaps nice enough to include in an update....  :D

I successfully created a custom section_group called _translated_ with a working custom image.

translated.ini
translated.png

I can't figure out how to get any "console" images to display in the background for the game list.  The rom images show up, but no custom console image.

I copied the snes folder from resources, modified the images, and renamed folder "translated" before uploading back to the resources folder ( I just get a big red X instead of a console image.  Same result if I use the stock snes images.  I'm placing the folders with images here:

/media/data/local/home/.simplemenu/themes/default/resources/translated
(and...)
/media/data/local/home/.simplemenu/themes/GBZ35Remix/resources/translated

I tried in upper case as well.   

I can't figure out where it's looking to pull these images from.

"translated.ini" 

[CONSOLES]
consoleList = TRANSLATED

[TRANSLATED]

execs = /media/data/apps/snes9x.opk
romDirs = /media/SDCARD/ROMS/TRANSLATED/
romExts = .sfc,.zip,.sfc,.smc

Thanks for any insight.   This a great app and thank you for making it.

**Comment by fgl82** [comment]
Hi @Jerry-in-WA , sure, if you send me the themes I can include them! my email is nomeacuerdotuemail@gmail.com. Glad you figured it out.
