### ISSUE TITLE
ScummVM resources (Default theme)

### ISSUE THREAD

**Issue by XargonWan** [fgl82/simplemenu#121]
[SCUMMVM]
headerBackGround = cc6601
headerFont = 94da0a
bodyBackground = f6e6a4
bodyFont = 000000
selectedItemBackground = 62a108
selectedItemFont = 000000
logo = resources/scummvm/logo.png
system = resources/scummvm/system.png
background = resources/scummvm/background.png

[scummvm.zip](https://github.com/fgl82/simplemenu/files/5010621/scummvm.zip)

**Comment by XargonWan** [comment]
Feel free to integrate it into the theme.

**Comment by fgl82** [comment]
I've gotten rid of the default theme, please feel free to make a theme of your own and publish it with these sections added, I don't have the time to maintain themes :)
