### ISSUE TITLE
MS-DOS & PokemonMini resources (default theme)

### ISSUE THREAD

**Issue by XargonWan** [fgl82/simplemenu#122]
[POKEMON MINI]
headerBackGround = 99b7ea
headerFont = FFFFFF
bodyBackground = dce2e2
bodyFont = 050505
selectedItemBackground = 42427C
selectedItemFont = ffffff
logo = resources/pokemonmini/logo.png
system = resources/pokemonmini/system.png

[pokemonmini.zip](https://github.com/fgl82/simplemenu/files/5010717/pokemonmini.zip)

[MS-DOS]
headerBackGround = 0000aa
headerFont = ffffff
bodyBackground = 000000
bodyFont = FFFFFF
selectedItemBackground = 0000aa
selectedItemFont = ffffff
logo = resources/msdos/logo.png
system = resources/msdos/system.png
background = resources/msdos/background.png

[msdos.zip](https://github.com/fgl82/simplemenu/files/5010718/msdos.zip)

**Comment by fgl82** [comment]
I've gotten rid of the default theme, please feel free to make a theme of your own and publish it with these sections added, I don't have the time to maintain themes :)
