### ISSUE TITLE
Simple Menu Crashes / Issues (RG350M) 

### ISSUE THREAD

**Issue by mmoscketti** [fgl82/simplemenu#124]
Hi, I’ve installed and configured simple menu on the RG350M and it intermittently crashes, going to a black screen that I have to reboot to device menu in order to get out.  It tends to occur when scrolling through the console emulators.  The black screen also happens sometimes when trying to quit out of Simple Menu, in which you have to reboot to get out of as well. (NOTE:  If default is set, it rebooted to a black screen and the only way to fix this was to go in the sbin and remove the Frontend start).  This was the only way I was able to return back to the devices original menu.

I really love Simple Menu when it's working, however with the continuous crashes it makes it really hard to enjoy it.  If there is anyway to fix this for the RG350M please let me know.  

Thank you and I appreciate all the hard work you have put in!

**Comment by dscx** [comment]
Do you have any logging setup? If not, open config.ini in the .simplemenu folder and change line 2 to this: `logging_enabled = 1`

I believe default launcher is broken on the 350m currently, but this could be from a bad opk or something.

**Comment by mmoscketti** [comment]
Hi Dan,

Thank you for the response back.  Yes logging is already enabled.

**Comment by dscx** [comment]
Ok i have this fixed thanks to #126

You must make these edits to frontend_start without removing the file from the device. Use vi to edit in place

**Comment by mmoscketti** [comment]
Awesome! Thank you!  Will definitely try it out.

**Comment by fgl82** [comment]
@mmoscketti I'm assuming this is fixed, closing the issue
