### ISSUE TITLE
The "default launcher" option does not work on RG350/RG350M

### ISSUE THREAD

**Issue by CodeEtienne** [fgl82/simplemenu#125]
The file  /media/data/local/sbin/frontend_start contains a typo:

elif [ -f /media/sdcard/apps/SimpleMenu-RG-350.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/sdcard/apps/SimpleMenu-RG-350m.opk
elif [ -f /media/data/apps/SimpleMenu-RG-350m.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/data/apps/SimpleMenu-RG-350.opk

Should be:

elif [ -f /media/sdcard/apps/SimpleMenu-RG-350.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/sdcard/apps/SimpleMenu-RG-350.opk
elif [ -f /media/data/apps/SimpleMenu-RG-350m.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/data/apps/SimpleMenu-RG-350m.opk

**Comment by fgl82** [comment]
Fixed by @andrewjennings, thanks!
