### ISSUE TITLE
The "default launcher" does not work for Pocket Go v1 

### ISSUE THREAD

**Issue by mawiseman** [fgl82/simplemenu#127]
I have a Pocket Go v1 and would like to use SimpleMenu as the default menu but it will not load by default

1. Follow the setup instructions for **Instructions Bittboy / Pocket Go**: https://github.com/fgl82/simplemenu/releases/tag/6.1
2. Open simplemenu
3. Press start to get to settings and set "Default Launcher" = yes
4. Press start to get back to simplemenu
5. Reboot the device
6. simplemenu is not launched by default

**Comment by mawiseman** [comment]
I was just able to resolve it when i found an old linux machine
- Open /rootfs/etc/main
- Comment out the reference to gmenu2x and add a direct link to simplemenu 
```
#cd /mnt/gmenu2x; ./gmenu2x
cd /mnt/simplemenu; ./simplemenu
```

**Comment by nicosensei** [comment]
Hi, actually it does not work on the latest 1.3.3 CFW, used to work with 1.3.2 (which generates an autoexec.sh file).

**Comment by andresito-dev** [comment]
The same thing happens to me. 
In CFW 1.3.3 if I put the simple menu as the default launcher it hangs after the pocket go logo.
If you edit the autoexec.sh you will see that it says SimpleMenu and not simplemenu. Anyway, I tried both ways.
Any solution?

**Comment by fgl82** [comment]
@nicosensei, this looks like a CFW 1.3.3 issue, not simplemenu. Does that CFW still use an autoexec.sh file?
