### ISSUE TITLE
System pics not displayed correctly on 350m

### ISSUE THREAD

**Issue by golovushkin** [fgl82/simplemenu#128]
You can see on photo...

![10090E64-474B-4380-84B8-2BB4688FEC91](https://user-images.githubusercontent.com/70581201/91849490-d7d27480-ec64-11ea-8515-54a2ff7d6df2.jpeg)

**Comment by fgl82** [comment]
@golovushkin: I'm releasing a new version tomorrow. please let me know afterwards if that one fixes the issue

**Comment by PonyOny** [comment]
I'm having the same issue on my RG350M with latest version :(

**Comment by fgl82** [comment]
Hello, I plan to take a look at these issues in January.

Thanks for the report.

**Comment by fgl82** [comment]
This is fixed
