### ISSUE TITLE
some games don't launch properly in PocketGo v1

### ISSUE THREAD

**Issue by mawiseman** [fgl82/simplemenu#129]
I have just tried Pokemn to load a number of pokemon games via simplemenu and they all fail
the load a white screen.
when you press X / Y you hear a beep but that is all

if i exit simplemenu they load successfully via gmenu2x

here is where i got pokemon from
https://www.downloadroms.io/gameboy-advance-rom-pokemon---fire-red-version-v11/

simplemenu v6.1

**Comment by dscx** [comment]
If you're working with GBA titles, see below.

There is a typo in handhelds.ini (in .simplemenu/section_groups )for the GBA emulator - it must be case-matched with the actual emulator name. Should look like this:

execs = /media/data/apps/ReGBA.opk

**Comment by fgl82** [comment]
@mawiseman please check @dscx comment
