### ISSUE TITLE
Playstation bin files

### ISSUE THREAD

**Issue by joelvdc** [fgl82/simplemenu#130]
I haven't seen anyone talking about this and it is not really an issue, but maybe more like a feature request regarding PSX games. I love the way simple menu is set up, but my PSX game list has a ton of duplicates due to the multiple bin files some games have. Is there a way to get around it and have only one entry per game? I would look much better and tidy.

**Comment by dscx** [comment]
Couple options here:

https://www.reddit.com/r/miniSNESmods/comments/7nx6z3/guide_how_to_convert_psx_multiple_discs_game_in/

**Comment by joelvdc** [comment]
> Couple options here:
> 
> 
> 
> https://www.reddit.com/r/miniSNESmods/comments/7nx6z3/guide_how_to_convert_psx_multiple_discs_game_in/

Yeah, well.. I know I can convert everything to pbp but I was hopping that was not necessary :/

**Comment by fgl82** [comment]
You can just list the .bins or.cues,I don't remember which ones were the
ones you are supposed to launch

**Comment by joelvdc** [comment]
Each disc will have at least one bin file and one cue file, so you will not avoid multiple entries by choosing one or the other. In some cases one disc can have several tracks and that will be reflected on the bin files, where you will find one per track, the tomb raider games are an example of that I think. And the bin files are the ones you should be running I believe, listing only the cue files won't work.

**Comment by fgl82** [comment]
Ah, well, then I guess it's not possible then

**Comment by dscx** [comment]
PBP is not necessary, but you're right you will have a bin and cue for each disc. If you name them well, you can tell them apart, but you can at the minimum combine a disc's bin files into a single one. Simplemenu config will let you organize them a bit more, excluding cue files from the list, iirc.

**Comment by joelvdc** [comment]
That's cool, I guess I will invest some time tidying up my collection. Thanks :)
