### ISSUE TITLE
Favorites on PG2v2

### ISSUE THREAD

**Issue by joelvdc** [fgl82/simplemenu#131]
So I got simple menu to work on my PG2v2 and I really like it! However, I can't access the favorites. I can add games to the favorites and I can see them on my computer when I open the specific file, but pressing L2 is not doing anything.

I am using the rg350 opk because the PG2 opk boots into a black screen, but I have the L2 button mapped to 303 in the input file (I believe that is correct?). I am on stock firmware (not using rogue for now due to the sound crackling issues), but I believe that is not an issue as everything else is working fine.

**Comment by fgl82** [comment]
I don know what mapping L2 is on the PG2v2, as I don own the device. Maybe they remapped the button from v1. If I find out what code you need, Iĺl let you know here.
