### ISSUE TITLE
Multitrack/multidisk games support

### ISSUE THREAD

**Issue by XargonWan** [fgl82/simplemenu#132]
I think a multitrack/multidisk games support is needed, for example a lot of PSX and Sega CD games got their cd as multitrack/multidisk:

- Game (Track 1).bin
- Game (Track 2).bin
- Game (Track 3).bin

- Game 2 (Disk 1).bin
- Game 2 (Desk 2).bin

**Comment by fgl82** [comment]
I have no idea how to do this, since I'm not even aware how other frontends tackle this situation:)

**Comment by fgl82** [comment]
I think what you need is the PBP format, which holds multiple discs in one file. Closing this issue.
