### ISSUE TITLE
PICO-8 media folder

### ISSUE THREAD

**Issue by XargonWan** [fgl82/simplemenu#137]
Can you please insert that if the system is PICO-8 (or the roms extension is .png) it search the media in ./ instead of ./media?
So the cover art will be recursively the png roms themselves?

**Comment by fgl82** [comment]
I will add a feature so you can overwrite the main media config in every section, leaving this open until then.

**Comment by fgl82** [comment]
Fixed, will be released in 9.4

**Comment by fgl82** [comment]
Won't need to change anything, it will just work that if a png file is the rom, it will use itself as the picture

**Comment by gladel** [comment]
What if user wants a different preview, say a user is using screenshots in all systems. Wouldn't it have inconsistencies with the entire aesthetics of that user's Simplemenu setup?

**Comment by fgl82** [comment]
Yes, but I already changed it from that because people didn't want to duplicate screenshots for what was already a png, so it's staying like this now

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
