### ISSUE TITLE
Anbernic RG-280V

### ISSUE THREAD

**Issue by Belchine** [fgl82/simplemenu#141]
Hello,

Do you test on RG280 V?
Autoboot doesn't function.

Belchine

**Comment by fgl82** [comment]
@Belchine Hi, sorry, I don have that console so I can test it there

**Comment by Belchine** [comment]
Ok. Are you interested to receive one Sample?
Like i'm Anbernic reseller, i Can do it for you...
Belchine

**Comment by fgl82** [comment]
Oh, sure, if you are ok with that it would be great.

I am located in South America though, just in case.

You can reach me at nomeacuerdotuemail@gmail.com and we can continue from
there.

Thanks!
