### ISSUE TITLE
Crash on opening any game RG350M

### ISSUE THREAD

**Issue by TmDobbin** [fgl82/simplemenu#145]
Hi, just dropped the .opk into the apps folder, configured all the .ini files etc and everything is working great, but every time I go to open an app or a game in an emulator or anything it crashes back to gmenu immediately. I'm using Rogue CFW 1.7.11 (Not sure if that makes a difference, would prefer to continue using it if possible) The ini files are absolutely correct with the execs etc, I've checked them multiple times. I can provide any more information if needed. Thanks in advance!

**Comment by fgl82** [comment]
Hi, I don't know what could be wrong, but I plan on releasing a more stable
version after january 4th. Maybe that will fix your issues.

**Comment by TmDobbin** [comment]
Thank you! Looking forward to then.

**Comment by fgl82** [comment]
@TmDobbin 6.9 is out, can you check now?

**Comment by fgl82** [comment]
Closing this
