### ISSUE TITLE
Generic Linux battery level algorithm

### ISSUE THREAD

**Issue by docwhat** [fgl82/simplemenu#147]
I was just looking through the source to figure out what is needed to make the battery levels work.

Reading the [kernel docs](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power) leads me to propose this as a general algorithm:

1. Scan `/sys/class/power_supply/*` for the first directory with a file named `type` with the conents `Battery`.
2. Read the file `capacity`

This should work on all kernels newer than 2010.

I'll see about contributing a PR once I figure out how compiling and testing, etc. works.

**Comment by jaredreich** [comment]
A battery percentage in the corner would be just amazing. Maybe something like this...?

<img src="https://user-images.githubusercontent.com/8563847/128083633-e0b5985e-2837-476d-990f-18df8a91b51e.png" width=300 />

**Comment by fgl82** [comment]
Percentage is not possible with these consoles or too hard to achieve for me. I've implemented the same 5 level indicator gmenu2x has and that's good enough for me.

**Comment by fgl82** [comment]
Also, there's no capacity file on these consoles
