### ISSUE TITLE
Default Theme crashes on PSX, 6.6

### ISSUE THREAD

**Issue by IsonDaya** [fgl82/simplemenu#150]
When using the OPK-packed theme on a fresh install, the default theme crashes simplemenu when tabbing into Playstation category. Using a different theme works correctly and unpacking the default theme in the separate themes.zip into the themes folder resolves the issue.

**Comment by fgl82** [comment]
@IsonDaya please try again using 6.9

**Comment by fgl82** [comment]
Fixed
