### ISSUE TITLE
Removing text overlay for section groups? 

### ISSUE THREAD

**Issue by Localhorst86** [fgl82/simplemenu#153]
Hi.

Is it possible (maybe via theme) to hide the text overlay (e.g. "Consoles", "Handhelds" etc.) for the selection groups in the main menu or change its position? I intend to use simple menu to have a distinctive image for each selection group with a logo in the center, but this currently gets obstructed with the name of the selection group

**Comment by fgl82** [comment]
Hi, yes, there's a toggle in the theme file: display_section_group_name = 1

Change that to 0 or add it if it doesn't exist in your theme

________________________________
De: Localhorst86 <notifications@github.com>
Enviado: miércoles, 3 de febrero de 2021 08:29
Para: fgl82/simplemenu <simplemenu@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Asunto: [fgl82/simplemenu] Removing text overlay for section groups? (#153)


Hi.

Is it possible (maybe via theme) to hide the text overlay (e.g. "Consoles", "Handhelds" etc.) for the selection groups in the main menu or change its position? I intend to use simple menu to have a distinctive image for each selection group with a logo in the center, but this currently gets obstructed with the name of the selection group

**Comment by Localhorst86** [comment]
Does that need to go into the [GENERAL] and does it require any specific version of the menu?
Since I am on a RS-97 i am stuck to the version "This is the time to remember, cause it will not last forever"

**Comment by fgl82** [comment]
Ah, then you don't have that feature yet. Hopefully I will do a version for RFW in March



Sent from my Galaxy



-------- Original message --------

**Comment by Localhorst86** [comment]
Looking forward to that, thanks 😀
