### ISSUE TITLE
100% CPU Usage

### ISSUE THREAD

**Issue by tonificante** [fgl82/simplemenu#154]
Hi!

Just noticed that simplemenu is using 100% cpu the whole time at normal idle status in a normal RG350 with the latest release (6.6, SimpleMenu-RG-350.opk). I tested it connecting RG350 with usb cable and doing ssh to terminal, then calling 'top' to measure cpu usage, then in RG350 starting simplemenu.

![screen](https://user-images.githubusercontent.com/5147180/107069567-6fbf2600-67e2-11eb-818d-d049fa5829a0.jpg)

Greetings!

**Comment by fgl82** [comment]
Hi,

is this while in the settings screen? Or in any screen at all?
________________________________
De: tonificante <notifications@github.com>
Enviado: viernes, 5 de febrero de 2021 14:48
Para: fgl82/simplemenu <simplemenu@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Asunto: [fgl82/simplemenu] 100% CPU Usage (#154)


Hi!

Just noticed that simplemenu is using 100% cpu the whole time at normal idle status in a normal RG350 with the latest release (6.6, SimpleMenu-RG-350.opk). I tested it connecting RG350 with usb cable and doing ssh to terminal, then calling 'top' to measure cpu usage, then in RG350 starting simplemenu.

[screen]<https://user-images.githubusercontent.com/5147180/107069567-6fbf2600-67e2-11eb-818d-d049fa5829a0.jpg>

Greetings!

**Comment by tonificante** [comment]
I can't test it now, but it was for sure at rom list screen and I think it will probably be at the menu screen too

**Comment by tonificante** [comment]
I took a look in the code, you use SDL_PollEvent() to check for keypress. Maybe the function SDL_WaitEvent() is more appropriated in your scenario. You can see some additional information here: https://stackoverflow.com/questions/18860243/sdl-pollevent-vs-sdl-waitevent

**Comment by fgl82** [comment]
Thanks, I will take a look, although I never saw high cpu usage before.

Will keep this open.

Thanks.



Sent from my Galaxy


-------- Original message --------

**Comment by fgl82** [comment]
Fixed
