### ISSUE TITLE
New BittBoy v1 - how to switch between consoles?

### ISSUE THREAD

**Issue by toto99303** [fgl82/simplemenu#155]
Hello,

I have simplemenu running on my New BittBoy v1, but since there's no L1 R1 shoulder buttons is there any other way to cycle trough the different handhelds/consoles? A key combo?

Thanks!

**Comment by fgl82** [comment]
@toto99303 hi, please press the button located on the bottom (I think it's "A"  in the bittboy and, while holding it, press left or right)

**Comment by fgl82** [comment]
Answered, so closing
