### ISSUE TITLE
Games & APPS not show

### ISSUE THREAD

**Issue by ToniBC** [fgl82/simplemenu#158]
Hello, for a long time, I see that the Games & APPS section does not show anything, it is empty, that is, the rest of the sections, all work, consoles, arcades, computers, but the Games section remains soft and in Apps only 6 come out.

The machine I use in an RG350 and with the latest firmware from Rogue. Simplemenu 6.6 & 6.9

The file is configured as I show.

[CONSOLES]
consoleList = GAMES,APPS

[GAMES]
execs = #
romDirs = /media/data/apps/,/media/sdcard/apps/
romExts = .opk,.OPK
category = games

In the rest of the sections, everything works out, except in this one that does not show anything.

Some solution or something missing to put.

Thanks.

**Comment by fgl82** [comment]
Hi, please check if your folders are really named apps and not APPS

**Comment by fgl82** [comment]
Also you only have the games section, did you delete apps on purpose?

**Comment by ToniBC** [comment]
I only put that fragment because the other one is the same but with APPS. The folders have the same name, and the internal ones the same. With 6.1 (I think that's it), which is the one being used by the community, it works without problems, but with the new ones, everything is shown except the games and apps.

The internal memory folders are the same, there I have about 20 games and apps that are displayed in the normal menu, but not in the simple menu in these newer versions.

**Comment by ToniBC** [comment]
I need to test with 7.0, to see if the same thing happens or works well. When I can try it, I'll tell you.

**Comment by fgl82** [comment]
@ToniBC did you try it? I'm closing this bug if not, as no one else reported this.
