### ISSUE TITLE
Key repeat issues

### ISSUE THREAD

**Issue by jlafitte** [fgl82/simplemenu#159]
RG-350 with stock 1.51 firmware.  Pretty much all input seems to repeat way too fast for me.  It's very hard not to go through several menu items in settings or consoles when navigating through them.  It happens with analog stick, d-pad, buttons, shoulder buttons, etc.  I even went to older versions and I'm still seeing the issue.  I don't seem to have any problems with GMenu2x though.

I used Simplemenu a bit before and don't remember it being a problem.  The only difference between now and then was that I was using Rogue Firmware back then, but I went back to stock due to other issues I was having with Rogue.

**Comment by jlafitte** [comment]
Honestly, I'm starting to think it could be analog drift.  I almost always use the power + b option to use analog everywhere, if I disable it it doesn't seem to do it as easily.

**Comment by fgl82** [comment]
Did you find out if you are experiencing analog drift?

**Comment by jlafitte** [comment]
I am not sure.  I don't really see it in any other game/app, but turning off the left analog stick definitely resolves it for me in SimpleMenu.  I don't even think it's drift honestly, just the stick is just a little loose, maybe SimpleMenu is more sensitive to it for some reason?

**Comment by fgl82** [comment]
I really have no idea, turning the analog stick  on or off doesn't cause issue for me or anyone else, that I know of. Seems like a hardware issue

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jlafitte** [comment]
Yeah, it's likely something with mine.  I'll close this.
