### ISSUE TITLE
"Tidy rom names" option cuts off names without spaces after ROM name

### ISSUE THREAD

**Issue by Quad-Plex** [fgl82/simplemenu#160]
Given a ROM name such as `Wings(EU).gba`, the option "Tidy rom names" shortens it to `Wing`

I'm guessing this is because ROMs are expected to be named `Wings (EU).gba` with a space in-between the ROM name and region indicator.

A possible fix would be a check after removing the region indicator `(EU)` to only delete the character infront if it's a whitespace, this way no actual letters would end up being cut off, regardless of the space being there or not

**Comment by fgl82** [comment]
Fixed in the upcoming release
