### ISSUE TITLE
VICE (latest 17.02)

### ISSUE THREAD

**Issue by thesnable** [fgl82/simplemenu#163]
pymenu: PRGs show but dont run
gmenu: PRGs dont show

Directly via COmmander:
VICE runs
PRGs load fine (via VICE menu)

**Comment by fgl82** [comment]
Huh? :)

**Comment by thesnable** [comment]
SOrry :-D

Ok... it just doesnt seem to start a *.prg" file.

I can start it directly from the emulator

**Comment by fgl82** [comment]
So, if Im understanding you correctly:

1) The vice emulator uses "prg" files
2) you don't see these files in gmenu
3) you see these files in pymenu but they are not executed when launched
4) The same happens when using SimpleMenu

Are these statements correct?

**Comment by thesnable** [comment]
Sorry. I am not using simple menu. This doesnt seem to install on my RTFW 2.2 ... :-( Thought this was the SM. But it was the default menu.
