### ISSUE TITLE
Retro FW 2.2 simplemenu wont launch

### ISSUE THREAD

**Issue by thesnable** [fgl82/simplemenu#164]
Hi!

I have an RG300 and copied all files into apps.

Simplemenu wont launch

Whats the difference between -OD-BETA and -OD?
Which do i need to use?
Where do i need to put the assets?

Update:
.simplemenu is created

But launching both ops makes me go back to gmenu

ALso no shotcut shows up in the gmenu

Thanks

**Comment by fgl82** [comment]
None of those OPKs are for RFW. I'll put out an opk for RFW soon.
