### ISSUE TITLE
Big Cody theme, missing images for neogeo, gamegear, bbcmicro, atarist and atari5200

### ISSUE THREAD

**Issue by bo32** [fgl82/simplemenu#165]
Hi, thanks for the latest release and good job!
I've applied the Big Cody theme for my RG280V but looks like the image for neogeo section doesn't work.
In the archive attached to the release, looks like images are missing for sections neogeo, gamegear, bbcmicro, atarist and atari5200.

**Comment by fgl82** [comment]
Hello @bo32, I've created a new repository for Big Cody, https://github.com/fgl82/BigCody.
Please leave this and any other issues there so I can better track them

**Comment by fgl82** [comment]
Added the missing resources to the new repo, except for BBC Micro, which the original theme doesn't have.
