### ISSUE TITLE
RG350M "can't load libshake.so.2"

### ISSUE THREAD

**Issue by ElvisofDallas** [fgl82/simplemenu#167]
Hi - 

I'm using the RG350M with stock firmware that was compiled 7/6/2020. 

I've tried with the file on my "external" sd card and copying to the /data/apps and in both cases I get this error. It quickly flashes then goes back to the list of apps screen.

Any recommendations? I'm using the file in SimpleMenu-OD-BETA-640x480.zip. Not sure how to recompile from source as I use macOS. 

Thanks in advance for any guidance!

**Comment by fgl82** [comment]
Hello, it seems your fw is missing the shake library, try a different fw version (maybe even rogue or od beta)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Elvis of Dallas ***@***.***>
Sent: Sunday, May 30, 2021 6:31:49 PM
To: fgl82/simplemenu ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fgl82/simplemenu] RG350M "can't load libshake.so.2" (#167)


Hi -

I'm using the RG350M with stock firmware that was compiled 7/6/2020.

I've tried with the file on my "external" sd card and copying to the /data/apps and in both cases I get this error. It quickly flashes then goes back to the list of apps screen.

Any recommendations? I'm using the file in SimpleMenu-OD-BETA-640x480.zip. Not sure how to recompile from source as I use macOS.

Thanks in advance for any guidance!
