### ISSUE TITLE
[request] EasyRPG games section

### ISSUE THREAD

**Issue by Icing-weaponry** [fgl82/simplemenu#168]
In his current state simplemenu doesn't allow easyRPG games to be played on the RG280v (unsure if it's the case for other Ingenic device)

When launching easyRPG in the app list, the game option is greyed out (like if there were no games).

In gmenu2x, to launch an easyRPG game you need to use the "directory selector" and select the correct file to launch the game. Simplemenu doesn't have that function (launching the app directly in gmenu2x without the directory selector causes the same issue, no games)

A easyrpg section would be best if it's possible so we can launch the games directly from it and, of course, add pictures for each of them.

Thank you for your time,

**Comment by fgl82** [comment]
I'll take a look

**Comment by Icing-weaponry** [comment]
thanks a bunch!

**Comment by Icing-weaponry** [comment]
messing around with the favorites.sav section I was able to make it "work"
I changed one line to the following
PLAYSTATION;/media/sdcard/EasyRpg/off/off.exe; ;/media/sdcard/APPS/;EasyRPG_gcw0_rg350.opk;0;/media/sdcard/EasyRpg/off/;996

And now "off" appears in the favorite section.

I tried to add a custom section for easyRPG with the following settings as well and it works but you need to rename the "RPG_RT.exe" file to the game name or else it get confusing when 10 titles are all named "RPG_RT.exe"

[EASYRPG]
execs = /media/sdcard/APPS/EasyRPG_gcw0_rg350.opk
romExts = .exe
romDirs = /media/sdcard/EasyRpg/
scaling = 1

a good idea that I have no idea how to do it would be to take the file name of the folder in which the RPG_RT.exe file resides, most RPG maker games use the same structure so using the folder name instead of the file name would be good.

**Comment by fgl82** [comment]
Sorry, this is a naming issue then, since you were able to add a custom section.
I won't change the menu for this particular scenario.
Maybe in the future I won't list files recursively and allow navigation, which would solve your issue but it won't be soon, sorry.
