### ISSUE TITLE
Any chance of >v5.5 for RG-300?

### ISSUE THREAD

**Issue by jaredreich** [fgl82/simplemenu#169]
Thank you so much @fgl82 for this glorious piece of software. Just wanted to ask, is anything higher than v5.5 meant to work on RG-300? I tried every version down to 5.5 and that's the latest version that works with RG-300. Would be amazing to have the latest version for that device, but again, thank you very much for your time and effort! Cheers!

**Comment by fgl82** [comment]
Hi,

I will try to update the rg300 version this weekend or the next one

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jared Reich ***@***.***>
Sent: Saturday, July 3, 2021 12:08:30 AM
To: fgl82/simplemenu ***@***.***>
Cc: FGL82 ***@***.***>; Mention ***@***.***>
Subject: [fgl82/simplemenu] Any chance of >v5.5 for RG-300? (#169)


Thank you so much @fgl82<https://github.com/fgl82> for this glorious piece of software. Just wanted to ask, is anything higher than v5.5 meant to work on RG-300? I tried every version down to 5.5 and that's the latest version that works with RG-300. Would be amazing to have the latest version for that device, but again, thank you very much for your time and effort! Cheers!

**Comment by jaredreich** [comment]
Wow, that is amazing to hear. Thank you for all the work you've done for the retro community.

**Comment by fgl82** [comment]
Check the releases page :)

**Comment by jaredreich** [comment]
Wow, I just tried it and it works! Thank you so much @fgl82 !
