### ISSUE TITLE
Crashing in favorite mode / OD Beta

### ISSUE THREAD

**Issue by K9-711** [fgl82/simplemenu#172]
simplemenu 9.2 on OD Beta. In favorite mode, keep pressing down, it goes to the last entry and then starting new from the first entry. Do the opposite way, keep up button pressing simpemenu crashes randomly when first entry is reached and it wants to go to the end of the list.

**Comment by fgl82** [comment]
Thanks for reporting this.
This happens when your favorites count is divisible by the number of games per page (for instance, 30 favorites with pages of 15), and it's a bug I'm aware of and fixing soon.
If you add or remove a favorite it should work fine, but of course this is just a workaround.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: K9-711 ***@***.***>
Sent: Friday, July 16, 2021 9:51:03 AM
To: fgl82/simplemenu ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fgl82/simplemenu] Crashing in favorite mode / OD Beta (#172)


simplemenu 6.2 on OD Beta. In favorite mode, keep pressing down, it goes to the last entry and then starting new from the first entry. Do the opposite way, keep up button pressing simpemenu crashes randomly when first entry is reached and it wants to go to the end of the list.

**Comment by K9-711** [comment]
Cool. Thank you. Have a great Weekend.

**Comment by fgl82** [comment]
I was way off :)
I've found the real cause of the bug, I think, and have fixed it.
I'll probably publish the new version tomorrow.

**Comment by fgl82** [comment]
Please check if the new release fixes your issue

**Comment by K9-711** [comment]
Unfortunately it still crashes. To do a clean install I deleted the old simplemenu opk and the .simplemenu folder and then only copied section_groups folder and my favorites.sav

**Comment by fgl82** [comment]
Can you describe the steps you are following? I can't get it to crash after my fix..

**Comment by fgl82** [comment]
Please be thorough so I can reproduce it, as in:
1) Start the console
2) SimpleMenu is/isn't the default
3) Open section XXX
4) Etc.

**Comment by fgl82** [comment]
Also, try letting it create an empty favorites.sav, just in case, and see if adding and removing works fine with that, maybe the old file is corrupted somehow

**Comment by K9-711** [comment]
Ok, it also crashes when I add favorites to an empty favorites.sav by pressing X

What I do:

1. Starting the console (OD Beta)
2. SimpleMenu isn't set as default
3. I' using Bog Cody theme, but also tried it with the standard OA theme
4. In SimpleMenu I press L2 to enter favorites then A to open the list
5. As soon I press the arrow up button SimpleMenu crashes and the 'desktop' shows up.

**Comment by fgl82** [comment]
That's very strange, I definitely can't get it to happen.
What I suggest you try:
1) Delete the old opk from the console
2) Delete/Rename the .simplemenu folder
3) Reboot the console
4) Download 9.3
5) Copy 9.3 to the console
6) Run it,
7) Important: if you see the text saying "Copying files, wait" on the first run, then you can be sure you are in 9.3
8) Don't copy any of your old files except the section_group files
9) Delete last state.sav
10) Run simplemenu again
11) Go to a section that has games
12) Add a favorite
13) Press L2
14) Press A
15) Press Up

**Comment by K9-711** [comment]
Just something I realized. When I'm enter the favorite mode and press Up key it crashes. But when I press right and / or left to jump pages and then keep pressing Up it doesn't crash. 

Now I'll do your steps.

**Comment by K9-711** [comment]
Ok, I followed exactly your steps. No crashing. I can add several games from different sections. No crashing.

**Comment by fgl82** [comment]
ok, great, if it happens again, please let me know!

**Comment by K9-711** [comment]
Thank you. It works now also after I copied my old favorite.sav

Another question. But I don't know of this is related to SimpleMenu. To run arcade games I'm using the latest FBA. In FBA I see the games list in full name thanks to the alias.txt. In SimpleMenu I can see all the full names on other sections like GBA. SNES but not for Arcade/FBA.

**Comment by fgl82** [comment]
That's a config in the arcades.ini file inside the section_groups folder.
Check the path to the alias file, it should be: /media/data/local/home/.simplemenu/alias.txt

**Comment by fgl82** [comment]
Sorry, I was not clear, what I mean is that to see the full name, you always need an alias file and you can do that for any section.
But, in my experience, non-arcade roms from good sets already have their full names, hence, the tidy roms option

**Comment by fgl82** [comment]
This is in fact not related to simplemenu but with the name of your files.
You can define an alias for any section, if you want, but ideally you'd have the right names for your non arcade files

**Comment by K9-711** [comment]
I understand. Thanks fgl82 for everything.

**Comment by fgl82** [comment]
I think I misunderstood your question, you were asking about aliasing the files in arcade sections.
Check the config for those sections in arcades.ini
You should have this exact path:
aliasFile = /media/data/local/home/.simplemenu/alias.txt

**Comment by K9-711** [comment]
Yeah, you mentioned; aliasFile = /media/data/local/home/.simplemenu/alias.txt
 For some reason I had aliasFile = /media/local/home/.simplemenu/alias.txt

With that correction it shows now the name of the games instead of the rom names. That's great.

**Comment by fgl82** [comment]
The reason is that I had messed up in previous versions and left you with the wrong path ;)

**Comment by K9-711** [comment]
I'm glad you ported SimpleMenu to OpenDIngux. (Beta) Otherwise I would have stayed with the stock formware. SImpleMenu adds a lot of value to the console. That's for sure.
