### ISSUE TITLE
Older versions no longer available?

### ISSUE THREAD

**Issue by sebboop** [fgl82/simplemenu#184]
Hi, 

I prefer the control layout of previous versions but I don't have a local copy saved. Is it possible to still download the older versions somewhere, or to manually change the controls back to the previous ones?

Thanks!

**Comment by fgl82** [comment]
Hi, no, older versions are not available on purpose, as they frequently contain bugs not present on the newer ones.
On the other hand, I'm not planning  on going back to the old scheme, I may enable it as an alternate in the future.
I will close this but if I ever enable it again I'll make it evident in the release notes.
Regards.
