### ISSUE TITLE
Genre/Franchise section groups

### ISSUE THREAD

**Issue by Daeymon** [fgl82/simplemenu#190]
Is their any apetite to add support for multi-system custom sections, such as having a genre section group and each section is a different genre, containing all games of that genre, regardless of system. The same could be done for franchises.

[This is EmulationStation's equivalent](https://retropie.org.uk/docs/EmulationStation/#custom-collections)

Edit: I removed the stuff for help on a hacky workaround. I figured out something else that seems to be working. I feel the above is still a valid request though I know its a long shot.

**Comment by fgl82** [comment]
Sorry, I don't plan on adding this, no.
