### ISSUE TITLE
Custom Sortation

### ISSUE THREAD

**Issue by Daeymon** [fgl82/simplemenu#191]
Give us the ability to apply a Sort Name to a game. This could be done in a similar fashion to the alias file, except this name is strictly used for sortation, and is not displayed. This will be useful for making sure a series of games are in the correct order despite not putting numbers in the name.

**Comment by fgl82** [comment]
I'm not sure I fully understand, but I don't plan on implementing anything other than alphabetical sort for games, sorry.
