### ISSUE TITLE
Support for other emulators

### ISSUE THREAD

**Issue by jeanvincent** [fgl82/simplemenu#39]
Hi, can you add support for another emulators for the pocketgo in simplemenu ?

- can't launch roms on the MSX emulator (dingux-msx), close and return to simplemenu

- amiga (uae4all) and MAME

**Comment by fgl82** [comment]
Not sure, maybe those emulators don't support launching roms from the command line, I will look into it

**Comment by fgl82** [comment]
@jeanvincent 

are you able to launch roms for those emulators from the file selector in GMenuNX?

**Comment by fgl82** [comment]
Cosing this as it's not a bug but just a problem with those emulators that don't support launching roms passed as parameters
