### ISSUE TITLE
Screenshots zoomed in/wrong ratio on 'favorites' menu

### ISSUE THREAD

**Issue by therourke** [fgl82/simplemenu#50]
I am using Simplemenu on an rg350.

I have skraped screenshots and added to appropriate /media folders. When pressing Y on the main menu they work great and look perfectly formatted. But on the 'favorites' list (after pressing L2) the background screenshots appear zoomed in and stretched. It's like the menu resizes the background so you can only see the center of each image (they also appear stretched and blurred).

Any idea what is causing this?

**Comment by therourke** [comment]
Really got fingers crossed that this can be fixed :(

Thanks

**Comment by fgl82** [comment]
@therourke , hi, can you send me one of the affected pictures by PM on discord?

**Comment by therourke** [comment]
This has been fixed on latest update! Thanks. I have a new issue though! Please see issues
