### ISSUE TITLE
Execution problem in OPK

### ISSUE THREAD

**Issue by eduardofilo** [fgl82/simplemenu#61]
Hi. I have tried to use OPK installation of versions 3.2 and 3.3 and I have not succeeded. I have 'unsquashed' the OPK and added execution permission to `invoker.dge` and `simplemenu` files, then 'resquashed' and the program starts working.

Thanks for your program by the way.

**Comment by fgl82** [comment]
Hey @eduardofilo, or Hola, since I think you speak Spanish?

Thanks for the info, I will try to make sure the next release is right.

Would you please send me your resquashed OPKs?

I will close this as it's not a bug in the code, but will add a note to the release files later.

**Comment by fgl82** [comment]
Not a bug in the code

**Comment by fgl82** [comment]
@eduardofilo esto es genial!
http://apuntes.eduardofilo.es/2020-01-25-rg350_simplemenu.html

**Comment by eduardofilo** [comment]
I'm glad you like it. As probably you have seen, the OPK with fixed permissions is linked to that page:
http://apuntes.eduardofilo.es/files/posts/SimpleMenu-RG-350_fixed.opk
