### ISSUE TITLE
PocketGo 2 \ games apps not start

### ISSUE THREAD

**Issue by urby66** [fgl82/simplemenu#63]
Program is tried out with Pocketgo V2
Under Rogue FW 1.4 the application can start, but none of the programs started. After start any of the programs or games simplemenu exits.
Under the official "miyoo_clean_image_12_15_2019-2" simplemenu won't start at all.
After clean install of the firmware everything is the same.

**Comment by fgl82** [comment]
hi @urby66, can you please try version 4.1 and let me know if this is solved?

**Comment by urby66** [comment]
Yes, the 4,1 version is working perfectly now.
For autostart I have to rename the .opk to mach the file name on the "frontend_start". Now it is also working well.
Thanks for the great support!
