### ISSUE TITLE
Favorites is not working

### ISSUE THREAD

**Issue by GeekGuyMJ** [fgl82/simplemenu#66]
I love your program. I used your latest revision and now my favorites will not work. I am using a Pocket Go v2. The X  and L2 button does not seem to do anything within simplemenu. I would love to get that back. I started from scratch this time and didn't use a previous version.

**Comment by fgl82** [comment]
Hi, I will release a new version today, please let me know if that one still has the issue.
I will keep this open.

**Comment by GeekGuyMJ** [comment]
It works great! Thank you very much. The only suggestion I would add is some sort of confirmation after favoriting a game. :-)

**Comment by fgl82** [comment]
Hi, I'm sorry, I won't add that, I like to keep things snappy, imagine having to favorite 3 or 4 consecutive games and having to press X and A to get rid of the message every time. I know messages is what people are used to but... nah :)

**Comment by fgl82** [comment]
The rg350 vibrates when you favorite a game, that's a sort of confirmation.

**Comment by fgl82** [comment]
Anyway, since it works now, I'm closing this bug, thanks for reporting it.
