### ISSUE TITLE
State save doesn't seem to work for favorites menu

### ISSUE THREAD

**Issue by therourke** [fgl82/simplemenu#74]
I understand that the last_state file should save where I was last located in a menu. this works for individual systems, but upon returning to the favourite menu it always resets to the top of the alphabet. I tried deleting the state file and having simplemenu re generate it, but it's not made a difference.

Is this a bug or am I missing something?

Thanks

**Comment by fgl82** [comment]
Hi, this is a bug indeed!

I'll fix it next time, leaving this open meanwhile of course :)

Thanks for letting me know!

**Comment by fgl82** [comment]
Aaaand, it's fixed and added a bonus: before when exiting/launching while in favorites and coming back, you would get sent to the first section in a group, it forgot what section you were in before going to favorites. Not anymore.

**Comment by therourke** [comment]
Great!

**Comment by fgl82** [comment]
5.6 is out, please let me know if it works for you now

**Comment by therourke** [comment]
Hi... it seems to have fixed the save state when you change menus. BUT, if you load a game from favorites, and then exit the game (exit the emulator) then when it goes back to favorites it starts back at the beginning of the entire list.

Also, the flash/logo screen for 'favorites' doesn't exist anymore (when you switch from favorites to sections for instance). Was that intentional?

**Comment by fgl82** [comment]
Hey, it's not doing that for me.... The flash logo screen should be there as well. What you are describing is very strange indeed.

Did you start from scratch this time or just replaced the opk?

**Comment by fgl82** [comment]
Also, there's 5.6.1 now

**Comment by therourke** [comment]
I just did a full reinstall with 5.6.1 and the Favorites flash screen is still absent

**Comment by fgl82** [comment]
Think you link a picture or short video of what you mean?

**Comment by fgl82** [comment]
The only time you saw the favorites logo was when you were in fullscreen, by the way, it never flashed when going from sections to favorites in menu mode, I don't think.

**Comment by fgl82** [comment]
Still not able to replicate this. Can you post the steps you follow so I can try?

Thanks.

**Comment by fgl82** [comment]
@therourke I'm going to close this as no one else reported it and 6.0 is out. Feel free to let me know if I need to reopen it.

Thanks.
