### ISSUE TITLE
Version 5.5 don't start on my RG-350

### ISSUE THREAD

**Issue by Horus2020** [fgl82/simplemenu#77]
Hi.

My RG-350 has kernel version 3.12.0 and version system 1.5.1.
I've copied the version 5.5 of simplemenu.opk in 'media/data/apps' but when I click on its icon, in the application menu, the folder  in path 'media/data/local/home/.simplemenu' and relatives subfolders dont'are created and main menu is showed again. 
What can i do to fix it?

**Comment by fgl82** [comment]
Can you try 5.6? Thanks

**Comment by Horus2020** [comment]
I tried now version 5.6 of SimpleMenu, but also with this new version, it returns to the applications menu without creating any folder. I don't understand ... I eliminated all the emulators for which I had no Roms, thinking that the problem was that. But there is no log file from which you can understand why it crashes? I am very sorry,

**Comment by fgl82** [comment]
did you follow the instructions on 5.6, step by step?

**Comment by fgl82** [comment]
And are you sure you have 1.5.1?

**Comment by Horus2020** [comment]
The version should be 1.5.1 because I updated it in December, but it's not written anywhere. In Settings / System info it tells me:
Kernel version: 3.12.0-dingux+
Compiled on Mon Oct 21 23:25:10 CST 2019
Root file system version: gfbd89c09c
Compiled on Mon Oct 21 16:25:24 CEST 2019
Processor: JZ4770
Total RAM for applications: 510202 KB
Network Interfaces:
USB0 10.1.1.2

I followed your instructions placing the latest version of the SimpleMenu-RG-350.opk file in the 
'/media/data/apps/' folder; the icon appeared in the applications tab and I execute it, but it returns to the same screen without creating the folders in '/media/data/local/home'.
Isn't there too much '/local/' or path is incorrect ?

**Comment by fgl82** [comment]
Based in your description, my only advice at this point is that you seek out 1.5.1, make sure it's 1.5.1 and then flash that and try again.

From what you describe, I'm pretty sure you don't have 1.5.1, as it sounds like other cases I got that were using stock.

Please try that and report back.

I understand if you don't want to go through all that hassle for a launcher but I don't have any ideas about what else could be wrong, since I'm100% sure this works as described in the steps.

**Comment by Horus2020** [comment]
Thank you very much. You are great!!! Indeed the version was not 1.5.1.
I flashed the firmware using the 'rg350-update-2019-10-27-2.opk' file without having to open the console, and after restart, the version 5.6 of simplemenu started without problems. Thank you for replying immediately and for giving me the opportunity to use your beautiful menu.

**Comment by fgl82** [comment]
No problem, glad it works, closing the issue then.
