### ISSUE TITLE
Issues with File trees and Emulators?

### ISSUE THREAD

**Issue by phil8715** [fgl82/simplemenu#80]
Hi,

I've got the Simplemenu on my RG350. I'm running the latest Rogue firmware 1.7.9.9.

However I'm getting this message when I open a game: for example; /media/data/apps/oswan.opk NOT FOUND. 

I tried different paths made sure the text is case-sensitive, but I can't seem to see a solution. I can see the rom names but when I choose a rom to play, I get the above message.

Also the roms do work with the emulators when I launch them outside of Simplemenu.

Can you please help me with this issue?

Thank you in advance 

Phil Graham

**Comment by fgl82** [comment]
Apr, so you ONLY have this issue with Sean?

**Comment by phil8715** [comment]
no,
The only emulators that seem to work are:
Gamebatte
Gpsp
Pcsx4all
Unreal Speccy

Some display the rom lists. I have the emulators such as the Sega Genesis Plus GX but I don't have any roms for that actual emulator.

**Comment by fgl82** [comment]
The same logic is used for every emulator so, if some work and some don't, I think something must be wrong in the config

**Comment by phil8715** [comment]
The file path to the emulators are the same in all cases.

 It's basically saying the emulator is missing. When the emulator isn't
missing. Something isn't linking correctly.

The example I sent you for Wonderswan is the path to each emulator
obviously the emulator names are different.

I just can't it working. I followed the path from pcsx4all which I know
works and tried to replicate it.

But didn't work.

**Comment by fgl82** [comment]
I understand, would you like to paste two sections here, one that works and one that doesn't?

**Comment by phil8715** [comment]
This one works fine.

[GAME BOY]
execs = /media/data/apps/gambatte.opk
romDirs = /media/sdcard/ROMS/GB/
romExts = .gb

This one doesn't work.
[NES]
execs = /media/data/apps/fceux.opk
romDirs = /media/sdcard/ROMS/NES/
romExts = .nes,.zip

Note that the sd card is actually called sdcard.

My file path where the emulators are located is as shown below.
/media/data/local/home

**Comment by fgl82** [comment]
I don't see anything wrong there, would you like to send me the actual file? You can mail it to nomeacuerdotuemail@gmail.com

**Comment by phil8715** [comment]
I don't understand what you mean by send you a file?

**Comment by fgl82** [comment]
Send me the consoles.ini file you are editing

**Comment by phil8715** [comment]
sorry I didn't understand what you meant earlier.

Here is the file you requested.
[CONSOLES]
consoleList = NES,SNES,MASTER SYSTEM,SEGA GENESIS,SEGA CD,SEGA 32X,PLAYSTATION,NEO-GEO,PC ENGINE,PC ENGINE CD,ATARI 2600,ATARI 7800,

[NES]
execs = /media/data/apps/fceux.opk
romDirs = /media/sdcard/ROMS/NES/
romExts = .nes,.zip

[SNES]
execs = /media/data/apps/PocketSNES.opk
romDirs = /media/sdcard/ROMS/SNES/
romExts = .sfc,.zip

[MASTER SYSTEM]
execs = /media/data/apps/GenplusGX.opk
romDirs = /media/sdcard/ROMS/SMS/
romExts = .sms,.zip

[SEGA GENESIS]
execs = /media/data/apps/picodrive.opk,/media/data/apps/GenplusGX.opk
romDirs = /media/sdcard/ROMS/GENESIS/
romExts = .bin,.zip

[SEGA CD]
execs = /media/data/apps/Picodrive.opk
romDirs = /media/sdcard/ROMS/SEGA CD/
romExts = .cue

[SEGA 32X]
execs = /media/data/apps/Picodrive.opk
romDirs = /media/sdcard/ROMS/32X/
romExts = .32x

[PLAYSTATION]
execs = /media/data/apps/pcsx4all.opk
romDirs = /media/sdcard/ROMS/PS/
romExts = .mdf,.img,.bin,.zip

[NEO-GEO]
execs = /media/data/apps/fba.opk
romDirs = /media/sdcard/ROMS/NEOGEO/
romExts = .zip
aliasFile = ./resources/alias.txt

[PC ENGINE]
execs = /media/data/apps/temper.opk
romDirs = /media/sdcard/ROMS/PCE/
romExts = .pce,.zip

[PC ENGINE CD]
execs = /media/data/apps/temper.opk
romDirs = /media/sdcard/ROMS/PCECD/
romExts = .pce,.zip

[ATARI 2600]
execs = /media/data/apps/stella.opk
romDirs = /media/sdcard/ROMS/2600/
romExts = .bin,.BIN

[ATARI 7800]
execs = /media/data/apps/ProSystem.opk
romDirs = /media/sdcard/ROMS/7800/
romExts = .a78,.rom

**Comment by fgl82** [comment]
Remove the , after Atari800

ATARI 7800,

**Comment by phil8715** [comment]
I've taken out the .rom extension and .a78 is this correct?

Also I don't have any 7800 roms.

**Comment by fgl82** [comment]
I was only saying to remove the , from the top list

**Comment by fgl82** [comment]
consoleList = NES,SNES,MASTER SYSTEM,SEGA GENESIS,SEGA CD,SEGA 32X,PLAYSTATION,NEO-GEO,PC ENGINE,PC ENGINE CD,ATARI 2600,ATARI 7800,

Vs

consoleList = NES,SNES,MASTER SYSTEM,SEGA GENESIS,SEGA CD,SEGA 32X,PLAYSTATION,NEO-GEO,PC ENGINE,PC ENGINE CD,ATARI 2600,ATARI 7800

**Comment by phil8715** [comment]
I've taken the comma off the top line where the list of the consoles is.

It's made no difference.

**Comment by fgl82** [comment]
The fact that PSX works and NES doesn't is not making sense to me. You did say that psx worked, right?

**Comment by phil8715** [comment]
Yes correct.

**Comment by fgl82** [comment]
And are you 100% sure your fceux executable is named fceux.opk, matching case and everything?

**Comment by phil8715** [comment]
![IMG_20200503_213726](https://user-images.githubusercontent.com/64745626/80925338-ec6e3100-8d86-11ea-8783-260350cabca6.jpg)

**Comment by phil8715** [comment]
![IMG_20200503_213647](https://user-images.githubusercontent.com/64745626/80925341-f7c15c80-8d86-11ea-8bfa-03490d68de3c.jpg)

**Comment by fgl82** [comment]
I don't see the f eux opk there, just the .fceux folder

**Comment by phil8715** [comment]
![IMG_20200503_215756](https://user-images.githubusercontent.com/64745626/80925616-39eb9d80-8d89-11ea-982a-b8df05bd4f3a.jpg)

**Comment by phil8715** [comment]
![IMG_20200503_215950](https://user-images.githubusercontent.com/64745626/80925646-7919ee80-8d89-11ea-948b-cb4788f449c6.jpg)

**Comment by fgl82** [comment]
There's your pr0blem, the opk is not named fceux.opk

**Comment by phil8715** [comment]
So if I rename to fceux.opk and keep them in the same directory it should
work?

**Comment by phil8715** [comment]
Yep it certainly was.

I've renamed so far, Wonderswan, Sega Genesis, Snes. All work.

Thank you so much for your help

It's really appreciated.

**Comment by fgl82** [comment]
Either rename the opk or change the config in the ini file to match with the name you have

**Comment by fgl82** [comment]
Ah, you solved it, great! No problem.
