### ISSUE TITLE
Bug: no roms if first folder is empty

### ISSUE THREAD

**Issue by eduardofilo** [fgl82/simplemenu#83]
When there are two directories in a system and the first one is empty of ROMs, the list of games appears empty in frontend. For example with this configuration for Game Boy System:

```
[GAME BOY]
execs = /media/data/apps/gambatte-multi-r572u4-20200127.opk
romDirs = /media/data/roms/GB/,/media/data/roms/GB2/
romExts = .gb,.gz,.zip
```

![screenshot001](https://user-images.githubusercontent.com/2923728/81410051-6b28ec80-9140-11ea-823a-dfca4e980a70.png)

**Comment by fgl82** [comment]
Thanks so much for reporting it here. I will look into this for the next release or the next one after that

**Comment by fgl82** [comment]
@eduardofilo I have corrected this on this release, could you please try again and let me know if close this issue if it works?

**Comment by eduardofilo** [comment]
I have tried and yes, it works. Issue resolved.
