### ISSUE TITLE
Battery % on options screen?

### ISSUE THREAD

**Issue by JayCanuck** [fgl82/simplemenu#86]
I did see https://github.com/fgl82/simplemenu/issues/75 but was curious about proposing an alternative that wouldn't clash with the gorgeous theme as-is. There could be a Battery % label on the options screen.

It's convenient/easy to access the option screen currently, and it's where similar system-level features like shutdown/reboot are accessed.  It would be incredibly handy to view the current battery level there. Waiting for the battery indicator isn't useful if you are aiming to maximize gametime and decide whether to take charger on-the-go. Plus it's handy for diagnostic purposes.

Obviously a personal preference thing; I imagine some people are ok without it, but just wanted to add my individual request on the matter, in an unobtrusive execution manner.

**Comment by fgl82** [comment]
Good idea, I will look into this for future releases.
Closing this as it's not an issue.
Thanks.
