### ISSUE TITLE
Amazing project!! A little suggestions

### ISSUE THREAD

**Issue by davefletch13** [fgl82/simplemenu#88]
Firstly I love it, I am using on my 350m as I have only a few different emulators on there I moved them all into one section and deleted the others, which makes it not show the section list when pressing B I don't know if you did this on purpose but its great!!!! Any idea when you are going to put the old default theme back in as I think it will look amazing without the top menu.

One suggestion is for a menu option to stop scaling boxart when in full screen mode leaving them centred in their native resolution, I think this will add alot to the overall aesthetic when in your original theme, also it will stop the landscape nes/snes boxart getting stretched to the full screen and probably be more efficient.

Let me know if you need any testing on the 350m (if you dont have one) will be happy to help

**Comment by fgl82** [comment]
Hi, no, I don't have a 350m.
About the default theme, it will be back on the next release, with a custom layout added in the same style. I'm not sure I know what you are talking about when you mention the "top menu"
About box art, maybe I can incorporate a switch in the theme for that, so some themes will be able to define stretched fullscreen, and some won't.
I'm closing this as it's not an issue with the menu.
For suggestions, please send them to me to nomeacuerdotuemail@gmail.com
Thanks.
