### ISSUE TITLE
build 6.1 - crash on start on PG2

### ISSUE THREAD

**Issue by egeon44** [fgl82/simplemenu#90]
6.0 work on my PG2 3.12.0-dingux
6.1 crash on start. 
Logs 
 ... | INFO | GAMES
... | ERROR | Nice, a critical error!!!

**Comment by fgl82** [comment]
Looks like some opk is making it crash, please delete apps_and_games.ini from section_groups, also te associated png, delete last state.sav and try to launch again

**Comment by fgl82** [comment]
Try using the rg350 opk and changing L2 in input.ini to 303

**Comment by egeon44** [comment]
On my PG2, rg350 opk 6.1 crash on start and dont create .simplemenu folder.
So i cant change input.ini

**Comment by fgl82** [comment]
Very strange, I've just had a pocket go 2 user fix it this way

**Comment by fgl82** [comment]
What rogue firmware are you using?

**Comment by egeon44** [comment]
i don't know, its the factory firmware, i only see 3.12.0-dingux.

**Comment by fgl82** [comment]
I'd strongly suggest you install rogue firmware, can't guarantee compatibility with stock firmware

**Comment by egeon44** [comment]
i'll try rogue 1.0.8 tomorrow. Thx for your time !

**Comment by egeon44** [comment]
it works with rg350opk.
