### ISSUE TITLE
Version 6.1 - Black screen when loading scummVM file list

### ISSUE THREAD

**Issue by goldmojo** [fgl82/simplemenu#91]
The application goes to black screen forever when parsing my scummVM file list.
The logs shows that the list of files is parsed and parsing suddenly stops.

I have no issue with any of the previous versions and with other rom folders.
Everything is back to normal when installing version 6.0.

Technical info : RG350 + Rogue Fw 1.7.9.9Z

**Comment by fgl82** [comment]
Is there anything particular about that rom folder? Does it have folders inside? Does it have a media folder? Please provide as much data as possible

**Comment by goldmojo** [comment]
For sure, I attached the full folder structure below.
[ScummVM.txt](https://github.com/fgl82/simplemenu/files/4691892/ScummVM.txt)

**Comment by fgl82** [comment]
Hmmm it's a long shot but what happens if you rename boxart to "media" as it's written in config.ini?

**Comment by goldmojo** [comment]
It is written "boxart" in my config.ini.

**Comment by fgl82** [comment]
Oh well, I'll try to reproduce it and see

**Comment by goldmojo** [comment]
Thank you.
I have seen that folder parsing method has been modified between 6.0 and 6.1, it may be a sideboard effect.
I will try to change my SD folder structure and make some new try in order to investigate.

**Comment by fgl82** [comment]
I haven't been able to get to this situation yet

**Comment by jalari06** [comment]
I am working on setting up my new RG350M and i am running into the same problem. I am not really sure what extension to tell it to parse, but I do know the emulator I am using (craigsc's scummvm-rg350-01132020.opk) would not work with them while they were zip files. I extracted each one to their own folder and then it would play them. Since every ScummVM game can have different files, I am not sure what extensions to tell it to look for. I really don't think it is going to work in this case since I dont think there just type of 1 file that the emulator launches, but looks at them all as a whole. For now I will just have to use the normal app to launch them.

**Comment by goldmojo** [comment]
I made some additional tests, the directory parsing crash when parsing Toonstruck directory.
When I remove this game, everything goes smoothly.

I attach the directory structure to this message, it may help you.
[Toonstruck_filelist.txt](https://github.com/fgl82/simplemenu/files/4872410/Toonstruck_filelist.txt)

I remove the game from my gamelist for now.

**Comment by goldmojo** [comment]
> I am working on setting up my new RG350M and i am running into the same problem. I am not really sure what extension to tell it to parse, but I do know the emulator I am using (craigsc's scummvm-rg350-01132020.opk) would not work with them while they were zip files. I extracted each one to their own folder and then it would play them. Since every ScummVM game can have different files, I am not sure what extensions to tell it to look for. I really don't think it is going to work in this case since I dont think there just type of 1 file that the emulator launches, but looks at them all as a whole. For now I will just have to use the normal app to launch them.

I forked craigsc's scummvm in order to make it work with SimpleMenu.
If interested, you can get this here : [https://github.com/goldmojo/scummvm-rg350/releases](https://github.com/goldmojo/scummvm-rg350/releases)
