### ISSUE TITLE
Problem with transparent logos

### ISSUE THREAD

**Issue by iroteta** [fgl82/simplemenu#94]
Device: RG350
Version of SimpleMenu: 6.1

Hi, i have a problem with transparent logos. I use logos with the system icon and transparent background. Then i have a background for all sections at "resources/general/simpleback.png", and in theme.ini the "menu_mode_logo_background" parameter has that value

menu_mode_logo_background = resources/general/simpleback.png

But it does not show that background and instead it shows a black background

**Comment by fgl82** [comment]
Yes, the menu_mode_logo_background feature was disabled, sorry.
