### ISSUE TITLE
Boot Fail - rg350m frontend_start references the non-"M" OPK

### ISSUE THREAD

**Issue by GNO21** [fgl82/simplemenu#95]
The **frontend_start** created for auto-boot for for the RG350m checks for the rg350m version of the OPK's existence but then tries to run the non-"M" rg350 version of OPK.  It does the opposite for the regular rg350.  This will lead to an apparent "Boot Hang".   You can still log in remotely however and fix things if this happens to you.

The Error is here in frontend_start:

>elif [ -f /media/sdcard/apps/SimpleMenu-RG-350.opk ]; then  
   &nbsp; &nbsp;  /usr/bin/opkrun -m default.gcw0.desktop /media/sdcard/apps/SimpleMenu-RG-350m.opk
elif [ -f /media/data/apps/SimpleMenu-RG-350m.opk ]; then
  &nbsp; &nbsp;     /usr/bin/opkrun -m default.gcw0.desktop /media/data/apps/SimpleMenu-RG-350.opk
elif [ -f /media/sdcard/apps/SimpleMenu-RG-350m.opk ]; then
  &nbsp; &nbsp;     /usr/bin/opkrun -m default.gcw0.desktop /media/sdcard/apps/SimpleMenu-RG-350m.opk

**Comment by fgl82** [comment]
Merged this, so closing the issue, thanks @andrewjennings !!!
