### ISSUE TITLE
Games list issue

### ISSUE THREAD

**Issue by XargonWan** [fgl82/simplemenu#97]
Version: 6.1
Device: RG-350
FW: Official

Every game for every platfom got a strange naming, for example:
Gameboy ColorMario Tennis

**Basically it puts the folder name before the game name.**
There is no subdir, each section is poiting at its own folder.

I tried to change the Tidy Game names, changed layout but doesn't help.

**Moreover not all boxart are visible, only for some systems.**
The boxarts are scraped with scraper and put in in the media folder inside each system folder.
Gameboy Color/media/Mario Tennis.zip

Some games are zipped some others are not.

Here is a screen and the log file:

![20200620_161340](https://user-images.githubusercontent.com/6771419/85203998-a60e6a80-b311-11ea-9b54-3f3dad230b1b.jpg)

[2020-06-20.log](https://github.com/fgl82/simplemenu/files/4808021/2020-06-20.log)

**Comment by goldmojo** [comment]
You must finish your rom paths using a /, for example :
romDirs = /media/sdcard/roms/FBA/

If you don't put this last /, you will encounter this behavior.

**Comment by XargonWan** [comment]
Solved, thanks.
